name: Build document

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install -y libproj-dev libgeos-dev libspatialite-dev libgdal-dev gdal-bin netcdf-bin
        gdal-config --version

    - name: Install geoextent and dependencies
      run: |
        python -m pip install --upgrade pip setuptools>=64
        pip install -e .[dev,test,docs]

    - name: Install additional documentation dependencies
      run:  |
        sudo apt update
        sudo apt install -y graphviz
    - name: Build the documentation
      run:  |
        cd docs
        make html
        cd build/html
        # Replace current build version and date
        CURRENT_VERSION=$(python -c 'from geoextent import __version__; print(__version__)')
        CURRENT_HASH=$(git log --pretty=format:'%h' -n 1)
        CURRENT_DATE=$(git show -s --format=%ci $CURRENT_HASH)
        echo $CURRENT_VERSION "@" $CURRENT_HASH $CURRENT_DATE
        sed -i "s/PLACEHOLDER_VERSION/$CURRENT_VERSION/g" index.html
        sed -i "s/PLACEHOLDER_HASH/$CURRENT_HASH/g" index.html
        sed -i "s/PLACEHOLDER_TIMESTAMP/$CURRENT_DATE/g" index.html
        cd ../../..
        ls

    - name: Deploy to Github pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/build/html # The folder the action should deploy.
        commit-message: Rebuild pages at ${{github.sha}} with branch ${{ github.ref }}
        git-config-name: Build bot <daniel.nuest@tu-dresden.de>
        git-config-email: daniel.nuest@tu-dresden.de
